use_frameworks!

platform :ios, '10.0'

target 'RMTutorialManagerKit_Example' do
  pod 'RMTutorialManagerKit', :path => '../'

  target 'RMTutorialManagerKit_Tests' do
    inherit! :search_paths

    
  end
end
